// Auto-generated by test_cov. Do not edit by hand.

import 'features\auth\presentation\view\View\login_test.dart' as features_auth_presentation_view_View_login_test;
import 'features\auth\presentation\view\View\signup_test.dart' as features_auth_presentation_view_View_signup_test;
import 'features\auth\presentation\view_model\signup_viewmodel\signup_viewmodel_test.dart' as features_auth_presentation_view_model_signup_viewmodel_signup_viewmodel_test;
import 'features\home\presentation\view\FeedPage_test.dart' as features_home_presentation_view_FeedPage_test;
import 'features\home\presentation\view_model\Comment_view_model\comment_view_model_test.dart' as features_home_presentation_view_model_Comment_view_model_comment_view_model_test;
import 'features\home\presentation\view_model\user_search_viewmodel_test.dart' as features_home_presentation_view_model_user_search_viewmodel_test;
import 'features\message\presentation\view\inbox_page_test.dart' as features_message_presentation_view_inbox_page_test;
import 'features\notification\presentation\view\notification_page_test.dart' as features_notification_presentation_view_notification_page_test;
import 'unit_test\api_service_unit_test.dart' as unit_test_api_service_unit_test;
import 'unit_test\validators_test.dart' as unit_test_validators_test;

void main() {
  features_auth_presentation_view_View_login_test.main();
  features_auth_presentation_view_View_signup_test.main();
  features_auth_presentation_view_model_signup_viewmodel_signup_viewmodel_test.main();
  features_home_presentation_view_FeedPage_test.main();
  features_home_presentation_view_model_Comment_view_model_comment_view_model_test.main();
  features_home_presentation_view_model_user_search_viewmodel_test.main();
  features_message_presentation_view_inbox_page_test.main();
  features_notification_presentation_view_notification_page_test.main();
  unit_test_api_service_unit_test.main();
  unit_test_validators_test.main();
}
