// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO_TynZthss9lGX8gHVOYCeZZivOLOLsQ',
    appId: '1:1038978543621:web:37f9f89b3390eb21946c6c',
    messagingSenderId: '1038978543621',
    projectId: 'softconnect-1082b',
    authDomain: 'softconnect-1082b.firebaseapp.com',
    storageBucket: 'softconnect-1082b.firebasestorage.app',
    measurementId: 'G-XK9XWZ13D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiH_OuwlwuWtUinpnBHhi889CFdQ6mB4',
    appId: '1:1038978543621:android:6cac2a9191b7a0ad946c6c',
    messagingSenderId: '1038978543621',
    projectId: 'softconnect-1082b',
    storageBucket: 'softconnect-1082b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN72AZrEjKW_NO89xd14jko_ELvACM8jc',
    appId: '1:1038978543621:ios:6b9e3083f28f59bb946c6c',
    messagingSenderId: '1038978543621',
    projectId: 'softconnect-1082b',
    storageBucket: 'softconnect-1082b.firebasestorage.app',
    iosBundleId: 'com.salin.firstproject.softconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN72AZrEjKW_NO89xd14jko_ELvACM8jc',
    appId: '1:1038978543621:ios:6b9e3083f28f59bb946c6c',
    messagingSenderId: '1038978543621',
    projectId: 'softconnect-1082b',
    storageBucket: 'softconnect-1082b.firebasestorage.app',
    iosBundleId: 'com.salin.firstproject.softconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO_TynZthss9lGX8gHVOYCeZZivOLOLsQ',
    appId: '1:1038978543621:web:a0384b6ecdcc7506946c6c',
    messagingSenderId: '1038978543621',
    projectId: 'softconnect-1082b',
    authDomain: 'softconnect-1082b.firebaseapp.com',
    storageBucket: 'softconnect-1082b.firebasestorage.app',
    measurementId: 'G-2XY6KDBEZN',
  );
}
